# Generated by Django 2.2 on 2021-09-03 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='user_2',
        ),
    ]
