# Generated by Django 2.2 on 2021-07-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_auto_20210723_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='login_app.User'),
        ),
    ]
