# Generated by Django 2.2 on 2021-09-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_remove_thread_user_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='msg_counter',
            field=models.IntegerField(null=True),
        ),
    ]
