# Generated by Django 2.2 on 2021-08-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_auto_20210727_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='profile_app.Team'),
        ),
    ]
