# Generated by Django 2.2 on 2021-09-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_profile_msg_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='msg_counter',
            field=models.IntegerField(default=0),
        ),
    ]
