# Generated by Django 2.2 on 2021-08-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20210807_2316'),
        ('profile_app', '0004_comment_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pkmn',
            field=models.ManyToManyField(to='main_app.Pokemon'),
        ),
    ]
