# Generated by Django 2.2 on 2021-09-05 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_auto_20210904_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='has_new',
            field=models.BooleanField(default=False),
        ),
    ]
