# Generated by Django 2.2 on 2021-09-02 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('gen', models.IntegerField(null=True)),
                ('sprite_url', models.CharField(max_length=200, null=True)),
                ('shiny_url', models.CharField(max_length=200, null=True)),
                ('art_url', models.CharField(max_length=200, null=True)),
                ('hp', models.IntegerField(null=True)),
                ('attack', models.IntegerField(null=True)),
                ('defense', models.IntegerField(null=True)),
                ('sp_attack', models.IntegerField(null=True)),
                ('sp_defense', models.IntegerField(null=True)),
                ('speed', models.IntegerField(null=True)),
                ('favorited_by', models.ManyToManyField(related_name='favorites', to='login_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('immune_to', models.ManyToManyField(related_name='no_effect_on', to='main_app.Type')),
                ('pkmn', models.ManyToManyField(related_name='types', to='main_app.Pokemon')),
                ('resists', models.ManyToManyField(related_name='weak_against', to='main_app.Type')),
                ('weak_to', models.ManyToManyField(related_name='strong_against', to='main_app.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_added', to='login_app.User')),
                ('likes', models.ManyToManyField(related_name='liked_reviews', to='login_app.User')),
                ('pkmn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_app.Pokemon')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='immune_to',
            field=models.ManyToManyField(related_name='immune_pkmn', to='main_app.Type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='resists',
            field=models.ManyToManyField(related_name='resistant_pkmn', to='main_app.Type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weak_to',
            field=models.ManyToManyField(related_name='weak_pkmn', to='main_app.Type'),
        ),
    ]
