# Generated by Django 2.2 on 2021-07-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='teams',
            field=models.ManyToManyField(related_name='team', to='login_app.User'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
