# Generated by Django 2.2 on 2021-08-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='height',
            new_name='attack',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='weight',
            new_name='defense',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sp_attack',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sp_defense',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('pkmn', models.ManyToManyField(related_name='types', to='main_app.Pokemon')),
            ],
        ),
    ]
