# Generated by Django 2.2 on 2021-08-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210807_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='immune_to',
            field=models.ManyToManyField(related_name='no_effect_on', to='main_app.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='resists',
            field=models.ManyToManyField(related_name='weak_against', to='main_app.Type'),
        ),
        migrations.AddField(
            model_name='type',
            name='weak_to',
            field=models.ManyToManyField(related_name='strong_against', to='main_app.Type'),
        ),
    ]
