# Generated by Django 2.2 on 2021-08-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210807_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='immune_to',
            field=models.ManyToManyField(related_name='immune_pkmn', to='main_app.Type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='resists',
            field=models.ManyToManyField(related_name='resistant_pkmn', to='main_app.Type'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='weak_to',
            field=models.ManyToManyField(related_name='weak_pkmn', to='main_app.Type'),
        ),
    ]
