# Generated by Django 2.2 on 2021-07-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bg_color',
            field=models.CharField(default='gray', max_length=20),
        ),
    ]
