# Generated by Django 2.2 on 2021-07-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bg_color',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='default_img',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
