# Generated by Django 2.2 on 2021-08-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_img',
        ),
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default=0, upload_to='images/'),
        ),
    ]
