# Generated by Django 2.2 on 2021-07-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20210707_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bg_color',
            field=models.CharField(default=272727, max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_img',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
