# Generated by Django 2.2 on 2021-08-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_auto_20210829_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='/media/images/0.png', upload_to='images/'),
        ),
    ]
