# Generated by Django 2.2 on 2021-07-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20210707_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_img',
            field=models.CharField(default='img/default-profiles/0.png', max_length=30),
        ),
    ]
