# Generated by Django 2.2 on 2021-08-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_auto_20210829_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='/default/0.png', upload_to='images/'),
        ),
    ]
