# Generated by Django 2.2 on 2021-07-15 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_auto_20210714_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follows',
            old_name='following_user_id',
            new_name='following_user',
        ),
        migrations.RenameField(
            model_name='follows',
            old_name='user_id',
            new_name='user_to_follow',
        ),
    ]
