# Generated by Django 2.2 on 2021-07-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0009_auto_20210714_2247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follows',
        ),
    ]
